sudo: false

language: node_js
node_js:
- "node"

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++" CC="gcc" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
- npm install -g typescript

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
  - codecov -f out/coverage/coverage-final.json