# -----------------------------------------------------------------------------------------------
#  Copyright (c) Red Hat, Inc. All rights reserved.
#  Licensed under the MIT License. See LICENSE file in the project root for license information.
# -----------------------------------------------------------------------------------------------

jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.8.1'
        inputs:
          versionSpec: 12.8.1
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          npm run test:coverage
        displayName: 'Run tests'
      - script: |
          node node_modules/codecov/bin/codecov -f out/coverage/coverage-final.json -t $(CODECOV_TOKEN)
        displayName: 'Upload coverage to codecov.io'
